# Generated by Django 4.2.13 on 2024-07-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fb_logging", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
