# Generated by Django 4.2.13 on 2024-07-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fb_logging", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
