# Generated by Django 4.2.13 on 2024-07-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fb_logging", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
